services:
  - type: web
    name: college-portal-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d796t014tr6s73cngk00-a.oregon-postgres.render.com;Port=5432;Database=collegemanagment;Username=collegemanagment_user;Password=cE27mbGpcd0w8ZbeZmfQ4NZXT87wafFb;Ssl Mode=Require
      - key: Jwt__SecretKey
        value: YourSuperSecretKeyForJWT2024CollegePortalLandmineSoft!@#$%
      - key: JWT_SECRET_KEY
        value: YourSuperSecretKeyForJWT2024CollegePortalLandmineSoft!@#$%
      - key: Jwt__Issuer
        value: CollegePortal.API
      - key: Jwt__Audience
        value: CollegePortal.Client
      - key: Jwt__ExpiryInHours
        value: "24"
